[serve]
# The address to serve on LAN.
address = "127.0.0.1"
# The address to serve on WAN.
# address = "0.0.0.0"
# The port to serve on.
port = 3000

[build]
target = "index.html"
dist = "dist"
BACKEND_URL="http://152.42.190.191:8080"
[[hooks]]
stage = "build"
command = "pwsh"
command_arguments = ["-Command", "Write-Host 'building new tailwind....'; npx tailwindcss -i ./src/styles/input.css -o ./src/styles/output.css"]

